name: EveryPennyCounts
favicon: null
layout_spectrum: 0.93294
typography_spectrum: 0.74278
title: 'Every Penny Counts, saving to spend more.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#939393'
    - '#e40000'
    - '#f4f5f4'
    - '#0072c3'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
