name: EveryPennyCounts
favicon: null
layout_spectrum: 0.93039
typography_spectrum: 0.35496
title: 'Every Penny Counts, saving to spend more.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfff2'
    - '#e43b00'
    - '#ffb6af'
    - '#f4b700'
    - '#ff7a6d'
  brandStrength: 0.7012967742048204
  lightness: 0.5097030680626631
  saturation: 0.8915730707813054
  rhythmicContrast: 0.166164563735947
purpose: []
