name: EveryPennyCounts
favicon: null
layout_spectrum: 0.6596
typography_spectrum: 0.74278
title: 'Every Penny Counts, saving to spend more.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfff2'
    - '#e43b00'
    - '#ffb6af'
    - '#f4b700'
    - '#ff7a6d'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
